name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    - name: Build the Docker image
      run: docker build . --file dockerfile --tag my-image-name
    - name: stoping  the existing docker container
      run: docker stop nodejs_app
    - name: removing the stoped container
      run: docker rm nodejs_app
    - name: starting the docker conatiner
      run: docker run -it -d -p 80:80 --name nodejs_app my-image-name   
